baseURL = 'https://jhonkleiber.github.io/'
languageCode = 'es-Es'
defaultContentLanguage = 'es'
title = 'Web Oficial'
theme = 'LoveIt'

[params]
  # Version del tema LoveIt
  version = "0.2.X"
  # Descripcion
  description = "Página Oficial ✓ | Jhon Kleiber es un cantante y compositor colombiano de pop latino y música popular. ¿Qué esperas para conocerlo? ¡Entra y escúchalo!"
  # site keywords
  keywords = ["Jhon Kleiber", "Kleiber"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "contacto"
    pre = ""
    post = ""
    name = "Contacto"
    url = "/contacto/"
    title = ""
    weight = 3

 # Configuracion del Header
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "images/logo.png"
      # title name
      name = ""

  # Configuracion del footer
  [params.footer]
    enable = true
    # Personalizar footer (Se puede usar HTML)
    custom = ''
    # Mostrar Hugo e informacion del tema
    hugo = false
    # Mostrar informacion de copyright
    copyright = true
    # Mostrar autor
    author = false
    # Sitio creado desde el año
    since = 2016
    # Informacion de la licencia (Se puede usar HTML)
    license = 'Todos los derechos reservados'

  # Configuracion de la página de Inicio
  [params.home]
    # LoveIt NUEVO | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.jpg"
      # Mostrar titulo en la pagina de Inicio (Se puede usar HTML)
      title = "¡Hola! Soy Jhon Kleiber"
      # Mostrar Subtitulo 
      subtitle = "Música: Más que pasión, filosofía de vida."
      # Mostrar animacion para el subtitulo
      typeit = true
      # Mostrar links sociales
      social = true
      # Disclaimer (HTML format is supported)
      disclaimer = "Soy un artista de pop y música popular nacido en Cali (Colombia), donde crecí corriendo entre las calles en pendiente y las fachadas de colores del barrio de Siloé; siempre acompañado por las melodías que nacían de la vieja radio frente a la que mis abuelos cantaban y tarareaban."
    # Home page posts
    [params.home.posts]
      enable = false

  # Redes sociales
  [params.social]
    GitHub = "jhonkleiber"
    Twitter = "jhonkleiber"
    Instagram = "jhonkleiber"
    Facebook = "jhonkleiberoficial"
    Telegram = "jhonkleiber"
    Youtubecustom = "jhonkleiber"
    Spotify = "jhonkleiber"
    Twitch = "jhonkleiberoffi"
    Email = "info@jhonkleiber.com"
    RSS = true

  # Author config
  [author]
    name = "Jhon Kleiber"
    email = "info@jhonkleiber.com"
    link = "https://jhonkleiber.com"



# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false